#!/bin/bash

set -o errexit

# Write a useful path in here when setting up course

REPO_DIR=`pwd`
TMPDIR=`mktemp -d`
TEAM=`echo $REPO_DIR | rev | cut -d'/' -f2 | rev`
TEAM_RESULTS="$RESULTS_DIR/$TEAM.scores.json"
echo "You are team $TEAM"

cd $MASTER_REPO_DIR
git clone $REPO_DIR $TMPDIR
RESULTS_FILE=$TEAM_RESULTS \
  test/score $TMPDIR/holes/*.rb
echo
rm -fr $TMPDIR
